import os 

SECRET_KEY = os.getenv("SECRET_KEY", None)
ALGORITHM = os.getenv("ALGORITHM", None)
ACCESS_TOKEN_EXPIRE_MINUTES = int ( os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 240))
REFRESH_TOKEN_EXPIRE_MINUTES= int ( os.getenv("REFRESH_TOKEN_EXPIRE_MINUTES", 560))