"""football

Revision ID: 7c89a1a882ae
Revises: 85fcaeb0bf4c
Create Date: 2022-10-10 15:46:06.614696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c89a1a882ae'
down_revision = '85fcaeb0bf4c'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('ft_competition',
  sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), autoincrement=True, nullable=False),
  sa.Column('register_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('name', sa.String(length=96), nullable=False),
  sa.Column('area_name', sa.String(length=96), nullable=False),
  sa.Column('code', sa.String(length=96), nullable=False),
  sa.PrimaryKeyConstraint('id'),
  comment='Table of Competition'
  )
  op.create_table('ft_teams',
  sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), autoincrement=True, nullable=False),
  sa.Column('register_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('name', sa.String(length=96), nullable=False),
  sa.Column('area_name', sa.String(length=96), nullable=False),
  sa.Column('tla', sa.String(length=96), nullable=False),
  sa.Column('short_name', sa.String(length=96), nullable=False),
  sa.Column('address', sa.String(length=256), nullable=False),
  sa.PrimaryKeyConstraint('id'),
  comment='Table of Teams'
  )
  op.create_table('tm_product',
  sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), autoincrement=True, nullable=False),
  sa.Column('register_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('name', sa.String(length=96), nullable=False),
  sa.Column('price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
  sa.PrimaryKeyConstraint('id'),
  comment='Table of products'
  )
  op.create_index(op.f('ix_tm_product_name'), 'tm_product', ['name'], unique=False)
  op.create_table('ft_coach',
  sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), autoincrement=True, nullable=False),
  sa.Column('register_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('name', sa.String(length=96), nullable=True),
  sa.Column('date_of_birth', sa.String(length=96), nullable=True),
  sa.Column('nationality', sa.String(length=96), nullable=True),
  sa.Column('id_team', sa.Integer(), nullable=True),
  sa.ForeignKeyConstraint(['id_team'], ['ft_teams.id'], ),
  sa.PrimaryKeyConstraint('id'),
  comment='Table of Coach'
  )
  op.create_index(op.f('ix_ft_coach_id_team'), 'ft_coach', ['id_team'], unique=False)
  op.create_table('ft_players',
  sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), autoincrement=True, nullable=False),
  sa.Column('register_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('name', sa.String(length=96), nullable=False),
  sa.Column('position', sa.String(length=96), nullable=True),
  sa.Column('date_of_birth', sa.String(length=96), nullable=True),
  sa.Column('nationality', sa.String(length=96), nullable=True),
  sa.Column('id_team', sa.Integer(), nullable=True),
  sa.ForeignKeyConstraint(['id_team'], ['ft_teams.id'], ),
  sa.PrimaryKeyConstraint('id'),
  comment='Table of Players'
  )
  op.create_table('ft_teams_competition',
  sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), autoincrement=True, nullable=False),
  sa.Column('register_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('id_competition', sa.Integer(), nullable=True),
  sa.Column('id_team', sa.Integer(), nullable=True),
  sa.ForeignKeyConstraint(['id_competition'], ['ft_competition.id'], ),
  sa.ForeignKeyConstraint(['id_team'], ['ft_teams.id'], ),
  sa.PrimaryKeyConstraint('id'),
  comment='Table of TeamsCompetition'
  )
  op.create_index(op.f('ix_ft_teams_competition_id_competition'), 'ft_teams_competition', ['id_competition'], unique=False)
  op.create_index(op.f('ix_ft_teams_competition_id_team'), 'ft_teams_competition', ['id_team'], unique=False)
  op.create_table('tm_product_metrics',
  sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), autoincrement=True, nullable=False),
  sa.Column('register_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('id_product', sa.Integer(), nullable=False),
  sa.Column('id_user', sa.Integer(), nullable=True),
  sa.Column('times_queried', sa.Integer(), nullable=False),
  sa.ForeignKeyConstraint(['id_product'], ['tm_product.id'], ),
  sa.ForeignKeyConstraint(['id_user'], ['tm_usuario.id'], ),
  sa.PrimaryKeyConstraint('id'),
  comment='Table of products metrics'
  )
  op.create_index(op.f('ix_tm_product_metrics_id_product'), 'tm_product_metrics', ['id_product'], unique=False)
  op.create_index(op.f('ix_tm_product_metrics_id_user'), 'tm_product_metrics', ['id_user'], unique=False)
  op.create_table('tm_tweets',
  sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), autoincrement=True, nullable=False),
  sa.Column('register_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=False),
  sa.Column('text', sa.String(length=256), nullable=False),
  sa.ForeignKeyConstraint(['user_id'], ['tm_usuario.id'], ),
  sa.PrimaryKeyConstraint('id'),
  comment='Table of Tweets'
  )
  op.create_index(op.f('ix_tm_tweets_user_id'), 'tm_tweets', ['user_id'], unique=False)
  op.create_table('tm_user_subscribers',
  sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, cycle=True), autoincrement=True, nullable=False),
  sa.Column('register_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('modified_date', sa.TIMESTAMP(), nullable=False),
  sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=False),
  sa.Column('subscriber_id', sa.Integer(), nullable=False),
  sa.ForeignKeyConstraint(['subscriber_id'], ['tm_usuario.id'], ),
  sa.ForeignKeyConstraint(['user_id'], ['tm_usuario.id'], ),
  sa.PrimaryKeyConstraint('id'),
  comment='Table of user_subscribers'
  )
  op.create_index(op.f('ix_tm_user_subscribers_subscriber_id'), 'tm_user_subscribers', ['subscriber_id'], unique=False)
  op.create_index(op.f('ix_tm_user_subscribers_user_id'), 'tm_user_subscribers', ['user_id'], unique=False)
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_tm_user_subscribers_user_id'), table_name='tm_user_subscribers')
  op.drop_index(op.f('ix_tm_user_subscribers_subscriber_id'), table_name='tm_user_subscribers')
  op.drop_table('tm_user_subscribers')
  op.drop_index(op.f('ix_tm_tweets_user_id'), table_name='tm_tweets')
  op.drop_table('tm_tweets')
  op.drop_index(op.f('ix_tm_product_metrics_id_user'), table_name='tm_product_metrics')
  op.drop_index(op.f('ix_tm_product_metrics_id_product'), table_name='tm_product_metrics')
  op.drop_table('tm_product_metrics')
  op.drop_index(op.f('ix_ft_teams_competition_id_team'), table_name='ft_teams_competition')
  op.drop_index(op.f('ix_ft_teams_competition_id_competition'), table_name='ft_teams_competition')
  op.drop_table('ft_teams_competition')
  op.drop_table('ft_players')
  op.drop_index(op.f('ix_ft_coach_id_team'), table_name='ft_coach')
  op.drop_table('ft_coach')
  op.drop_index(op.f('ix_tm_product_name'), table_name='tm_product')
  op.drop_table('tm_product')
  op.drop_table('ft_teams')
  op.drop_table('ft_competition')
  # ### end Alembic commands ###
