"""football

Revision ID: 971eccf3af83
Revises: 7c89a1a882ae
Create Date: 2022-10-10 15:47:20.933158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971eccf3af83'
down_revision = '7c89a1a882ae'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('ft_teams', 'area_name',
              existing_type=sa.VARCHAR(length=96),
              nullable=True)
  op.alter_column('ft_teams', 'tla',
              existing_type=sa.VARCHAR(length=96),
              nullable=True)
  op.alter_column('ft_teams', 'short_name',
              existing_type=sa.VARCHAR(length=96),
              nullable=True)
  op.alter_column('ft_teams', 'address',
              existing_type=sa.VARCHAR(length=256),
              nullable=True)
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('ft_teams', 'address',
              existing_type=sa.VARCHAR(length=256),
              nullable=False)
  op.alter_column('ft_teams', 'short_name',
              existing_type=sa.VARCHAR(length=96),
              nullable=False)
  op.alter_column('ft_teams', 'tla',
              existing_type=sa.VARCHAR(length=96),
              nullable=False)
  op.alter_column('ft_teams', 'area_name',
              existing_type=sa.VARCHAR(length=96),
              nullable=False)
  # ### end Alembic commands ###
